// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfPKpez5XDsP0HIbODT6DUPHa8MJnHLE',
    appId: '1:67897154165:web:580222c18986940acf363c',
    messagingSenderId: '67897154165',
    projectId: 'foname-1b065',
    authDomain: 'foname-1b065.firebaseapp.com',
    storageBucket: 'foname-1b065.appspot.com',
    measurementId: 'G-J0ER5CFD6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSin2JtMP2hn9Q85Zxz0WQ78hXNrSNAPI',
    appId: '1:67897154165:android:ce16ab98552d35e1cf363c',
    messagingSenderId: '67897154165',
    projectId: 'foname-1b065',
    storageBucket: 'foname-1b065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03sWpuBwObYZr9rYYLLt420KRywC33gI',
    appId: '1:67897154165:ios:9899c55b49ab8af0cf363c',
    messagingSenderId: '67897154165',
    projectId: 'foname-1b065',
    storageBucket: 'foname-1b065.appspot.com',
    iosBundleId: 'com.example.payment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA03sWpuBwObYZr9rYYLLt420KRywC33gI',
    appId: '1:67897154165:ios:9899c55b49ab8af0cf363c',
    messagingSenderId: '67897154165',
    projectId: 'foname-1b065',
    storageBucket: 'foname-1b065.appspot.com',
    iosBundleId: 'com.example.payment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_BoG_0xaSrf56GP3zoQSzCHt_6sOcR8c',
    appId: '1:67897154165:web:7eda139b6649c52ccf363c',
    messagingSenderId: '67897154165',
    projectId: 'foname-1b065',
    authDomain: 'foname-1b065.firebaseapp.com',
    storageBucket: 'foname-1b065.appspot.com',
    measurementId: 'G-4LL0FX2R5E',
  );
}
